config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :recipes do
    resources :doses, only: [:new, :create]
    resources :ratings, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
  validates :amount, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :star, presence: true
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :ratings, dependent: :destroy
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_name,
  against: [ :name ],
  using: {
    tsearch: { prefix: true }
  }

  def avg_rating
    if ratings.first
      (ratings.all.map { |rating| rating.star }.sum / ratings.all.count).floor(2)
    else
      0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredients = Ingredient.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    params[:ingredients].each_with_index do |ingredient, index|
      @dose = Dose.new(recipe: @recipe, ingredient_id: ingredient.to_i, amount: params[:amount][index].to_i)
      render :new, status: :unprocessable_entity unless @dose.save
    end
    redirect_to recipe_path(@recipe)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :amount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @rating = Rating.new(rating_params)
    @rating.recipe = @recipe
    if @rating.save
      redirect_to recipe_path(@recipe)
    else
      render "recipes/show", status: :unprocessable_entity
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:star)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
    if params[:query].present?
      @recipes = Recipe.search_by_name(params[:query])
    end
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'recipes/list', locals: { recipes: @recipes }, formats: [:html] }
    end
  end

  def show
    @doses = Dose.where(recipe_id: Recipe.find(@recipe.id))
    @rating = Rating.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipe_path(@recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @recipe.update(recipe_params)
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, status: :see_other
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :instruction, :photo)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doses/new.html.erb
<div class="container mt-3">
  <div class="mb-3">
    <h1>Add Ingredients to <%= @recipe.name %></h1>
    <%= simple_form_for([@recipe,@dose]) do |f| %>
      <% @ingredients.each do |ingredient| %>
        <div class="dose-form mt-3 mb-3">
          <%= f.hidden_field :ingredient_id, value: ingredient.id, name: "ingredients[]" %>
          <%= f.hidden_field :amount, label: ingredient.full_name %>
          <%= ingredient.full_name %>: <%= f.input_field :amount, name: "amount[]" %> g
        </div>
      <% end %>
      <%= f.button :submit, "Add Ingredients", class: "text-btn" %>
    <% end %>
  </div>
  <%= link_to "Back", recipe_path(@recipe), class: "back-btn"  %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-lewagon">
  <div class="container-fluid">
    <ul class="navbar-nav me-auto">
      <%= link_to recipes_path, class:"text-decoration-none" do %>
        <li class="nav-item">
          <h1 style="color: #742225; font-family: 'Rubik Dirt', cursive;">Choco BitterSweet</h1>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <%= link_to "Add new recipe", new_recipe_path, class: "choco-btn" %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Choco BitterSweet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: "all" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
  </head>
  <body class="background" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= asset_path('background.jpg') %>');">
    <div>
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/recipes/_list.html.erb
<div class="row row-cols-2 row-cols-lg-3 row-cols-lg-4", data-refresh-list-target="list">
  <% recipes.each do |recipe| %>
    <%= link_to recipe_path(recipe), class: "link" do %>
      <div class="card col mb-4">
        <%= recipe.photo.attached? ? cl_image_tag(recipe.photo.key, class:"card-img-top") : image_tag("images.png", class:"card-img-top") %>
        <div class="card-body">
          <h5 class="card-title"><%= recipe.name %></h5>
          <%= render 'star', recipe: recipe %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/_star.html.erb
<p class="card-text me-1">
  <% recipe.avg_rating.to_i.times do %>
    <i class="fa-solid fa-star"></i>
  <% end %>
  <% if (recipe.avg_rating - recipe.avg_rating.to_i) > 0.25 %>
    <i class="fa-regular fa-star-half-stroke"></i>
    <% (5 - recipe.avg_rating.to_i - 1).times do %>
      <i class="fa-regular fa-star"></i>
    <% end %>
  <% else %>
    <% (5 - recipe.avg_rating.to_i).times do %>
      <i class="fa-regular fa-star"></i>
    <% end %>
  <% end %>
</p>

app/views/recipes/edit.html.erb
<div class="container mt-3">
  <h1>Edit <%= @recipe.name %></h1>
  <div class="mb-3">
    <%= simple_form_for(@recipe) do |f| %>
      <%= f.input :name %>
      <%= f.input :instruction %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: "text-btn" %>
    <% end %>
  </div>
  <%= link_to "Back" , recipe_path(@recipe), class: "back-btn" %>
</div>

app/views/recipes/index.html.erb
<div class="container" data-controller="refresh-list">
  <%= form_with url: recipes_path, method: :get, html: { class: 'mb-5', data: { refresh_list_target: 'form' } } do |f| %>
    <%= f.text_field :query,
    class: "form-control mt-3 search-bar mb-0",
    placeholder: "Find a recipe",
    value: params[:query],
    data: {
      refresh_list_target: 'searchInput',
      action: "keyup->refresh-list#update"
    }
  %>
    <%# <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <%= render 'list', recipes: @recipes %>
</div>

app/views/recipes/new.html.erb
<div class="container mt-3">
  <h1>Add a new recipe</h1>
  <div class="mb-3">
    <%= simple_form_for(@recipe) do |f| %>
      <%= f.input :name %>
      <%= f.input :instruction %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, "Add Recipe", class: "text-btn" %>
    <% end %>
  </div>
  <%= link_to "Back" , recipes_path, class: "back-btn" %>
</div>

app/views/recipes/show.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-5">
      <h1><%= @recipe.name %></h1>
      <div class="d-flex">
        <%= render 'star', recipe: @recipe %>
        <%= (@recipe.avg_rating) %>
      </div>
      <div class="mt-3">
        <%= @recipe.photo.attached? ? cl_image_tag(@recipe.photo.key) : image_tag("images.png") %>
      </div>
      <div class="mt-5">
        <%= link_to "Edit", edit_recipe_path(@recipe), class: "text-btn" %>
        <%= link_to "Delete", @recipe, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-btn" %>
      </div>
      <p class="mt-5"><%= @recipe.instruction.gsub(",", ", ") %></p>
      <div class="mb-3">
        <h3>Add Rating</h3>
        <%= simple_form_for([@recipe, @rating]) do |f| %>
          <div class="star-rating mb-5">
            <% 5.times do |i| %>
              <input type="radio" name="rating[star]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
            <% end %>
          </div>
          <%= f.button :submit, "Submit Rating", class: "text-btn" %>
        <% end %>
      </div>
      <%= link_to "Back", recipes_path, class: "back-btn" %>
    </div>
    <div class="col-5">
      <h2>Ingredients</h2>
      <% @doses.each do |dose| %>
        <p><%= dose.ingredient.full_name %>: <%= dose.amount %>g</p>
      <% end %>
      <% unless @recipe.doses.first %>
        <%= link_to "Add ingredients", new_recipe_dose_path(@recipe), class: "back-btn"  %>
      <% end %>
    </div>
  </div>
</div>